---
- name: Disable Swap
  shell: swapoff -a
  become: true
  become_user: root

- name: Remove Swap Entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/.*swap'
    state: absent
  when: ansible_swaptotal_mb > 0  # Only remove if swap is present

- name: Remove Swap File
  shell: rm -f /swapfile
  when: ansible_swaptotal_mb > 0  # Only remove if swap is present
