---
- name: Disable Swap
  ansible.builtin.command: swapoff -a
  become: true
  become_method: sudo

- name: Remove Swap Entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/.*swap'
    state: absent
  when: ansible_swaptotal_mb > 0  # Only remove if swap is present

- name: Remove Swap File
  ansible.builtin.file:
    path: /swapfile
    state: absent
  when: ansible_swaptotal_mb > 0  # Only remove if swap is present
